### ISSUE TITLE
[Feature] add change event to ngx-timepicker-field

### ISSUE THREAD

**Issue by billyjov** [Agranom/ngx-material-timepicker#207]
native input field provide change events, so it may be usefull to have something like this for the  `ngx-timepicker-field` and others

**Comment by binDongKim** [comment]
Desperately wanting this feature!

**Comment by JoeyVinyard** [comment]
In the meantime you can register a change function using the registerOnChange method in the timepicker-field class.

**Comment by rakia** [comment]
This requirement + having [minutesGap] attribute for ngx-timepicker-field + Bug Fix: "a manual input for 2 numbers in ngx-timepicker-field is not always correctly displayed" are crucial for my case to be able to switch from ngx-bootstrap timepicker to this library.

I really want to use it because we'are already using angular material in our app, but i'm waiting until the 3 mentioned requirements will be ready in the next release (I hope).

**Comment by Agranom** [comment]
Added `@Output() timeChanged`. Update to v.5.3.0

**Comment by ronny98** [comment]
Hii @Agranom what if we want 24 hr format output while (timeSet) output event in Ts file whatever we have AM PM means to keep it default format we got event output like 3:15 pm instead of calculating time in 24 formats and gives 15:15. Currently, I have to calculate it manually. Is there any solution???

**Comment by jgu7man** [comment]
> Added `@Output() timeChanged`. Update to v.5.3.0

I'm trying use the Output event but always retrun `undefined`.

Can you tell me i'm using correctly?

```
<ngx-timepicker-field #picker 
(timeChanged)="setTime()" 
[format]="24" 
[defaultTime]="formatTime(Now)"
></ngx-timepicker-field>
```
