### ISSUE TITLE
24hr format, invalid dateTime

### ISSUE THREAD

**Issue by llecorguille** [Agranom/ngx-material-timepicker#285]
Hello,

There is a bug with the 24hour format, when trying to set the time between 00:01 and 00:59, the timepicker output "invalid dateTime".

![timepicker1](https://user-images.githubusercontent.com/19268011/74016184-4d59b900-4992-11ea-984e-639a93e9b58c.png)
![timepicker2](https://user-images.githubusercontent.com/19268011/74016196-4fbc1300-4992-11ea-97fe-61cf4c6054e9.png)

**Comment by Agranom** [comment]
Hello

I cannot reproduce it 
https://prnt.sc/r03shx

**Comment by llecorguille** [comment]
Looks like it comes from my PC. Bug is still there on my PC, but its working fine on Raspberry. I have the same UTC settings o.o

Is there a way to know why the DateTime is invalid ?

**Comment by Agranom** [comment]
Can you provide me your PC time settings? I'll try to figure out the issue

**Comment by chorpler** [comment]
I get the same thing on a Mac (Mojave 10.14.5) in 24-hour mode. If I set it to exactly midnight, it sets the time to 24:00, so I think maybe the `Invalid DateTime` error is caused by a value of 24:01 to 24:59?

**Comment by florisvanderhaar** [comment]
Same issue here, MacOS Catalina.

It seems to happen on the latest versions of all chromium browsers with Chromium 80.0.3987+. I've tested Google Chrome (Stable, Dev, Canary), Brave, even Microsoft Edge Chromium.

Chrome for Android might also break now the Chrome version has been updated to 80, as will the other browsers after an update.

**Comment by Agranom** [comment]
I see. I'm getting the same error now. Will check it

**Comment by csegyud** [comment]
Hi, I can also see this on Windows 10 64 bit & Chrome 80. While on Firefox it seems to be working, so I suspect that it may be s.g. wrong in Chrome. BTW, I cannot recall to see it on earlier versions of Chrome - maybe others can confirm it. 

FYI, in Chrome dev tools I stopped at your **set value** function in **ngx-material-timepicker.js** and found that **TimeAdapter.formatTime** function returns **'24:45'** for an actualy value of **'00:_:45'**. 
Also, in further functions called the locale is set to default locale which is en-US, and the time format is set to 'H:m' while it is imported with `NgxMaterialTimepickerModule.setLocale('da-DK')` and the time format should be 'HH:mm'. 

![image](https://user-images.githubusercontent.com/5646497/75115273-173c5a80-565d-11ea-8fa6-e70cc601f454.png)

I hope it gives you meaningful info. I'm not sure though if you can do anything with it, since it looks like a Chrome bug.

**Comment by adriankott** [comment]
Hello , same issue Windows 64 Chrome  80.0.3987.116.

Than you for the great work and eagerly waiting for any updates on this issue.

**Comment by chorpler** [comment]
In the fork I made that I'm using right now, I ended up adding a test in `material-timepicker/time-adapter.ts` to the `static toLocaleTimeString()` method, where instead of just returning this:
```ts
DateTime.fromFormat(time, timeMask).setLocale(locale).toLocaleString(timeFormat);
```
it first checks the result to see if it ended up starting with `24:` and just changes the first two characters to `00` if so, then returns the output of that test.

It doesn't answer the question of why this started happening with Chrome 80, and I don't think it's exactly a general solution because some people might not always want it with the two-digit-hour format, but it's fine for what I'm doing at the moment.

**Comment by csegyud** [comment]
FYI, just got a report from my customer that the problem is also present on iPhone 7+ Safari. On my iPhone 6s Safari it's still working. So it is not just on Chrome.

**Comment by KirillTovpinets** [comment]
I faced the same issue in chrome, but on your demo page in 'ngx-timepicker-field' section, the bug is not reproduced
![Screenshot_36](https://user-images.githubusercontent.com/14245565/75429869-8797f400-595b-11ea-804f-985b3201a296.png)

**Comment by Agranom** [comment]
I'll try to fix till the end of this week

**Comment by Agranom** [comment]
The issue is resolved. Update to the latest version (v.5.4.0).

**Comment by csegyud** [comment]
@Agranom Great, thank you very much. The time picker now accepts the previously missing range.

But now I get a strange format. Although I set the ngModel (and defaultTime) to "**11:42**", the picker input displays "**11.42**" Please notice the dot instead of a colon. 

Note: On the below image I highlighted my model value with yellow bg. 

![image](https://user-images.githubusercontent.com/5646497/75624131-eb1b5f00-5bb1-11ea-8c42-ef6e66b2db2d.png)

Could you please have a look? Shall I open a new issue for this? 
Thx!

**Comment by Agranom** [comment]
@csegyud it's not a bug. I suppose you use `da-DK` locale. That locale has formatting with one dot

**Comment by csegyud** [comment]
Oh, you are right. I'm not Danish, I just work for them, but they have never complained about HH:mm.
I used da-DK before your last change and it showed HH:mm. Anyway, it's not a bug, sorry. 
Can I maybe overwrite this format somewhere? Thx.

**Comment by Agranom** [comment]
Format changed is because of luxon lib has upgraded. You can try to downgrade luxon to 1.11.0. It might help. Or just use another locale

**Comment by LukaszBalazy** [comment]
Is this valid? After updating to version 5.4.0 I'm now getting time as `24:05` instead of 00:05
@Agranom

**Comment by Agranom** [comment]
@LukaszBalazy it means that you're setting the wrong locale, which doesn't work with 24h format correctly. Which locale do you use?

**Comment by LukaszBalazy** [comment]
Oh true, didn't set any, so I was using the default one. Changed it and its working. Thanks a lot. :)

**Comment by Agranom** [comment]
Fixed it. Now you'll get '00:xx' time with default locale. Update to the latest version
