### ISSUE TITLE
cannot read property 'replace' of null on 24 Hrs format

### ISSUE THREAD

**Issue by faran-tenovos** [Agranom/ngx-material-timepicker#341]
I'm on angular 9.2.x and I've tried most versions up to 5.5.2. Here is how I reproduced the bug.
-> Select any time other than 00:xx 
-> Open Time Picker again select any time ranging in 00:xx
-> Now the Time Picker puts the value as 24:xx and opening it again it breaks.

![image](https://user-images.githubusercontent.com/60923612/81889830-f7fafc80-95bd-11ea-9401-9d986a2495c1.png)

**Comment by Agranom** [comment]
I'll check it

**Comment by anjaliTandel20** [comment]
I am getting the same issue while opening it again on edit mode.

**Comment by EdgarsJoja** [comment]
I had very similar issue. In my case this happened due to saving value in DB time column, which transformed it to H:i:s format (xx:yy:zz) and such error appeared when this value was being passed back for editing. Simple solution was to make sure that the retrieved value is in H:i (xx:yy) format.
Not sure if this would work for original 00:xx issue, but maybe it helps someone due to error message being basically the same.

**Comment by anjaliTandel20** [comment]
I think there is issue with displaying time as 24:30, It should be 00:30.

**Comment by Agranom** [comment]
Fixed in v5.5.3

**Comment by noamyg** [comment]
Still having this problem in 5.5.3

**Comment by kiknadze** [comment]
![image](https://user-images.githubusercontent.com/9992978/165375448-9d4e7698-72c6-4148-9df0-7650deba94d2.png)
Angular 12

**Comment by kiknadze** [comment]
Before open time component, I check if time format is correct.
It works for me:

`if (!moment(this.value, 'HH:mm', true).isValid()) this.value = null;`
